### PR TITLE
scripts for macOS VST2/VST3 installing, package-vst3.sh modification

### PR DESCRIPTION
**Pull request by esaruoho**
@kurasu @kzantow @abique @baconpaul @asimilon

Here are some tiny modifications and duplications to already existing scripts, with the point of view of placing the macOS VST2 or VST3 to the correct place, and fixing package-vst3.sh so it more accurately connects with VST3 instead of VST2..

Any thoughts would be appreciated.

### CODE REVIEW

**Comment by kzantow** [comment]
Might be worth noting in the README along with this that you need to run `sudo ...` the commands

**Comment by esaruoho** [comment]
@kzantow hold on.. run `sudo` the commands?

I didn't need to sudo to get `./installer-local-au.sh´ to run? :)

**Comment by esaruoho** [comment]
no worries @kzantow :) it's good to have some discussion about a PR before it gets merged in by @kurasu

**Comment by esaruoho** [comment]
@kzantow requested that this should be closed, so i'll close it.

**Pull request closed without merging**
