### PR TITLE
1.6 - UI Update

### PR DESCRIPTION
**Pull request by cyanit**
Finally its (pretty much) done. Changed some suttle things, I'm pretty happy with it. Also used af photo to get some nice lightning, I really hope that it'll look good.

This work is based on the original graphics, that Claes Johanson made. Also, Dave Palmer (@itsmedavep) made some awsome filter & envelope vectors I couldnt have done.
Should you have any suggestions, let me know! Im usually avalible via twitter (@cyanitofficial). Thanks again to Dave, I cant wait to see the new build working!

### CODE REVIEW

**Comment by cyanit** [comment]
pew, no conflicts. Hoped I didn't mess up anything with the directories...

**Comment by cyanit** [comment]
@baconpaul I think its now ready :)

**Comment by baconpaul** [comment]
How cool. I will take a look but may not be until Monday

But even before zoom we can use the 1.0 assets if they all fit I think.

Will be a bit of work to get a build together. Appreciate your patience.

**Comment by cyanit** [comment]
The assets should fit, only the about screen may look a bit empty.

**Comment by baconpaul** [comment]
Yeah I’m excited to look and try.  But can’t do that from my phone :)

I actually used surge 1.6 to make some music today - which was the reason I jumped in to help after all - and it felt really close to having another world class modern synth in my rig. This is a critical step.  Thank you!

**Comment by esaruoho** [comment]
@baconpaul how can i try this out?

**Comment by baconpaul** [comment]
@esaruoho short version: wait a bit.

longer version: write the right code

but I'm going to do that. It's raining here so I'm actually unexpectedly home. I'll give it a whirl.

**Comment by esaruoho** [comment]
i'll take the wait a bit route for 200€!

**Comment by baconpaul** [comment]
OK cool so I've figured out how to test this. I'm going to merge this PR but there's a bug. Doesn't matter though because no-one will use these skins unless you make a skin change which I'm not going to make permanent.

So you know here's an image of the original

screen shot 2019-01-05 at 3 48 35 pm

And here's an image using these vector skins

screen shot 2019-01-05 at 3 51 07 pm

and you can see immediately that it looks way sharper; but also that the knobs for all the sliders are missing!

So I'll debug that and put a comment on the original issue.

**Pull request merged**
