### PR TITLE
[WiP] Include configuration in bundle

### PR DESCRIPTION
**Pull request by kzantow**
Some drop-downs didn't work because they were expecting a file in `/Library/Application Support/Surge/configuration.xml`, which I assume was put there from an installer. This just moves it into the bundle and loads it from there. Also builds off of #69

### CODE REVIEW

**Comment by baconpaul** [comment]
Hi!

Thanks so much! But im not totally sure this is the right approach. Lots of things like patches and waves also come from lib/app support

#85 would fix this but today the post build local install script installer-local-au.sh sets up the app support dir

Since surgery uses filestystem heirarchg as category and has writeable patches, things will be outside the bundle so we just gotta write an installer.

Also check out #83 

Glad to be wrong! And super appreciate you jumping in!

**Comment by kzantow** [comment]
@baconpaul right, as indicated this is a WiP and shouldn't be merged as-is. Even without an installer, the bundle could include the bare minimum to at least get access to very basic presets for effects and get access to the waveform selector, otherwise the synth is fairly limited. Perhaps this could be written in code (I just added the `configuration.xml` for expediency.

For user-provided additional content, that could (and still is) be read from `/Library/Application Support/Surge/...`, especially things like additional waveforms for the wavetable oscillator, etc.. I did not even see the `installer-local-au.sh` 🤦‍♂️  but it would be nice to have VST2/3 work consistently with the AU version as well. I don't use AU ever, so I'm not familiar with the expectation from end users of having an installer vs. copying the `<plugin>.component`. For VST, quite a few simply provide the `<plugin>.vst` and let users just copy it to the right spot.

**Comment by esaruoho** [comment]
@kzantow well, let's see what `installer-local-au.sh` actually does and whether it could be modified into `installer-local-vst2andvst3.sh`..

**Comment by kzantow** [comment]
@esaruoho even if the "right" thing to do is put everything in `/Library/Application Support/...` I'd much rather just write a bit that runs at plugin startup and automatically does the install (copies the xml file, makes any directories that don't exist, etc). Having users run a script to set it up seems silly to me, especially since it's really just making sure one file is available at the beginning. Maybe this will change as patches/waveforms/etc. are added to the distribution, but it would be pretty easy to just include those in the bundle and copy/sync them to the `Application Support` location. I'm happy to write the code that does this, then we could very easily (I expect) alter the bundle to do one of those installers that is just "drag this file into this folder symlink". WDYT? cc. @baconpaul @esaruoho @kurasu

**Comment by esaruoho** [comment]
@kzantow hi, i pushed a PR #88 with (duplicated from installer-local-au.sh content modified to fit) `installer-local-vst2.sh` and `installer-local-vst3.sh` and modified the already existing `package-vst3.sh` .  any thoughts would be much appreciated.

**Comment by kzantow** [comment]
@baconpaul agree; I'll update #87  with the approach for review

**Comment by esaruoho** [comment]
@kzantow could this PR itself be closed if everyone's focusing on #87? we don't want to confuse @kurasu with too much work.. :)

**Comment by kzantow** [comment]
@esaruoho yeah, I'd say we close this one and focus on #87 ; I'm almost done with changes we discussed

**Comment by esaruoho** [comment]
@kzantow hmm .. did you just say that we close PR 87 and focus on #87 (same one)? :).. sorry, i'm easily confused. just trying to figure out where the "dump `.` and `..`" commit might be :)

**Comment by kzantow** [comment]
@esaruoho haha oops, i meant close #88

**Comment by esaruoho** [comment]
@kzantow ok, i closed #88

**Comment by kzantow** [comment]
Closing as superseded by #92

**Pull request closed without merging**
