### PR TITLE
Add Surge pdf manual to repo

### PR DESCRIPTION
**Pull request by esaruoho**
Now that @baconpaul got an AudioUnit (AU) created with a GUI - I think it's high time this repo have Surge.pdf, right?

@kurasu  hope that's fine with you?

### CODE REVIEW

**Comment by jsakkine** [comment]
Prefer not to add binaries to GIT repositories unless that is the last straw. Are there sources available for this. If not, would keep it out of the GIT as we can never update it anyway.

**Comment by jsakkine** [comment]
Better idea would be to redo it in ReStructedText/Sphinx and add a build target for it.

**Comment by esaruoho** [comment]
@jsakkine what's a ReStructuredText/Sphinx? I guess I could do copypasta work but maybe @kurasu has the originals of this?

**Comment by jsakkine** [comment]
http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

**Comment by jsakkine** [comment]
Could be other options. That is the only that what I'm familiar with because it is used in the Linux kernel.

**Comment by jsakkine** [comment]
"Kernel documentation with Sphinx, part 1: how we got here"
https://lwn.net/Articles/692704/
"Kernel documentation with Sphinx, part 2: how it works"
https://lwn.net/Articles/692705/

**Comment by baconpaul** [comment]
I agree we should write docs in a format which is editable in emacs (or vi or whatever) and makes web pages. I was thinking “markdown and pngs in a docs directory” but happy for whatever the doc writer chooses as long as we choose something!

**Comment by esaruoho** [comment]
@baconpaul i found it at http://vemberaudio.se/download/surge.pdf

basically, i think, i could type it up to some markdown format, but would rather not, as it is 38 pages long. but if @kurasu tells us: the original master document does not exist, i can type it up no problem. It'll just take me some time.

I'm mostly interested in there being a reasonably opensourced format for this, so would edge towards markdown. something that we can bake a PDF out of, for sure. as i'd want it to not be _only_ online. i need to dump it onto an iPad for instance. or have it available for offline use as a downloadable PDF.

**Comment by esaruoho** [comment]
posted a question at #78 - let's hope Claes answers it!

**Comment by esaruoho** [comment]
merged into #68, closing

**Pull request closed without merging**
