### PR TITLE
Convert oscillator to over-aligned allocations

### PR DESCRIPTION
**Pull request by jsakkine**
Still working getting a Windows environment up and running. However, based on my test programs #188, I strongly believe that this should be correct. @kurasu, can you check if this works for you? If it does this looks like a trivial job finish up.

### CODE REVIEW

**Comment by jsakkine** [comment]
rebased

**Comment by jsakkine** [comment]
I can test this myself at least soonish with Windows once I get it installed to VirtualBox.

**Comment by jsakkine** [comment]
rebased.

**Comment by kurasu** [comment]
Tested on windows and works fine, looks sane

**Comment by jsakkine** [comment]
Awesome.

**Pull request merged**
