### PR TITLE
Cocoa UI on MacOS in Audio Unit with Zoom, LFO display, and several other fixes.

### PR DESCRIPTION
**Pull request by baconpaul**
Hi

This diff is the PR we need to build and correctly run the gui on MacOS. Nowhere near as big as the one to get the synth running, but quite a lot harder, mostly because I'm not really a cocoa expert and the documentation on the internet just sorta stinks. But I figured it out eventually and here we go.

The discussion of this is in #61 

Thanks to @esaruoho for feedback and stuff. 

Once this is done, I think the only step left to actually being able to do a 64 bit audio unit mac release of surge is making a packager rather than the hack job scripts I have together to build this now.

Appreciate any feedback, corrections, changes, concerns, or critiques.

### CODE REVIEW

**Comment by esaruoho** [comment]
You guys might appreciate this screenshot that @baconpaul attached into #61 
49939329-84296180-feaa-11e8-999a-c5dfc0b4960c-2

**Comment by esaruoho** [comment]
This really works and is a serious serious improvement, finally being able to see Surge on Logic Pro X and actually program it a little bit. @kurasu and @abique might have some insider knowledge as to what is missing or what doesn't work, but I'm able to load presets, program my own and whatever.

There's probably tons yet to be fixed but this is a major step forward. I hope we'll get this merged in asap.

**Comment by esaruoho** [comment]
Confirmed (by a friend): Ableton Live 10 will run this AudioUnit without issues (well, obviously there might be some issues with Logic Pro X + Ableton Live 10 running this, further down the line, but the synth UI booted up and stuff.

i'll see if I can get Renoise to show this somehow.

**Comment by esaruoho** [comment]
can confirm, Surge works with Ableton Live 10. Hot stuff!

surge_51-surge

**Comment by baconpaul** [comment]
Wahey! That’s super!

**Comment by esaruoho** [comment]
@baconpaul not as fully as in logic, though, for some reason, i can't click on the dropdown menu that would let me choose an effect to add to the chain. it works in logic but not on ableton live. how odd..

**Comment by esaruoho** [comment]
@kurasu hi, would you have time to take a look and merge this in? It works beautifully - any other additions would be iterative updates (fixing the LFO Wave at the bottom, etc)..

**Comment by baconpaul** [comment]
OK @esaruoho and @kzantow I just merged both zoomable-ui and the fix for the right mouse button into au-cocoaui-build so this pull request now gets me to fixing

#89 (broken install popup)
#83 (no LFO waveform)
#81 (fix zoom in surge)
#61 (create the cocoa ui)

I think it would be great if we could also include @kzantow std::filesystem fix and the documentation at least.  Do you guys have permission to add those to this PR? And if not, how do I grant it to you?

**Comment by esaruoho** [comment]
@baconpaul i don't have a way to write to your PR, and i'm not sure how to contribute to it.. except to maybe post a PR to your fork and you merge it into this.. but for now i'll probably try and see if @kurasu will merge #68 in and then i'll delete my fork, re-create it and hope it works better.

**Comment by baconpaul** [comment]
OK but doesn't #68 contain that weird memory diff we were talking about?

Anyway lets see what gets merged!

**Comment by esaruoho** [comment]
@baconpaul yeah it has the "merge from kurasu:master to esaruoho:master" diff.. i'm yet to figure out how to revert it out of it.

**Comment by baconpaul** [comment]
OK thanks to @kzantow who is marshaling together all the changes that he did, that I did and that @esaruoho did into one pull request #92. I have confirmed that PR #92 subsumes this code, and also adds a fix, and so is the better PR than this one to review. As such I'm closing this one.

**Pull request closed without merging**
