### PR TITLE
Readme.MD, Premake5, Swedish comment translation to English in code, au-package.sh quickfix, wavetable rmb quickfix, alert on mac if no configuration.xml

### LINKED ISSUE #29: Wavetable right click menu doesn't work
**Describe the bug**
No context menu (containing all the wavetables for easy selection) is shown when right-clicking the wavetable name.

**To Reproduce**
1. Right-click on the wavetable name.

**Expected behavior**
Right clicking the wavetable name should open a context menu with all the wavetables.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Host: FL Studio 12
 - Version: 12.0.5

**Additional context**
Context menu doesn't work in VSTHost either. Switching via the tiny arrows works though.

### LINKED ISSUE #67: Translate comments from Swedish to English
As @kurasu warned, a couple of comments were in Swedish. So I translated them to English, with Google Translate, some work by hand, and a lot of help by a friend.

Check the PR at #68

### LINKED ISSUE #77: std::filesystem stub on macOS returns . and .. in directory iteration
So std::filesystem isn't on Xcode 10 and the surge has a stubbed out implementation. I fixed a few bugs to get things running but directory iteration still returns "." and ".." in a way which leads to it showing up in menus.

screen shot 2018-12-14 at 3 00 06 pm
screen shot 2018-12-14 at 3 01 52 pm

So the trick is to filter appropriately in the hand crafted mac only directory iterator.

### LINKED ISSUE #89: Mac and Linux don't report broken installs to users
As discussed with @esaruoho and @kzantow both getting it to work without the ~/Library/App Support, the error message for an incomplete install is suppressed on mac and linux.

The code that needs fixing is in SurgeStorage.cpp

```
   string snapshotmenupath = datapath + "configuration.xml";

   if (!snapshotloader.LoadFile(snapshotmenupath.c_str())) // load snapshots (& config-stuff)
   {
#if !MAC && !__linux__
      MessageBox(::GetActiveWindow(), "Surge is not properly installed. Please reinstall.",
                 "Configuration not found", MB_OK | MB_ICONERROR);
#endif
   }
```

### PR DESCRIPTION
**Pull request by esaruoho**
This PR updates
- `README.md` (more links, moved to the bottom)
- `Premake5.lua` (spaces replaced with tabs, beautification)
- tons of files (Swedish comments translated into English by Google Translate and by hand).
- fixes `au-package.sh` text so it talks about AudioUnit and not AU
- takes @baconpaul 's quickfix for #29 and does that too (RMB to open wavetable dropdown menu)
- takes @baconpaul 's quickfix for #89 for mac (alert user if configuration.xml not present in `~/Library/Application Support/Surge` -folder
- takes @kzantow 's quickfix for #77 for mac (hides `.` and `..`)
- Merged Surge.pdf PR #74 into this PR

@kurasu @kzantow @abique thoughts appreciated.

heads up, @baconpaul - not sure if these help but just on the offchance they do, have fun!

Fixes #67  
Fixes #29  (Thanks @baconpaul!)
Fixes #89 (Thanks @baconpaul)
Fixes #77 (Thanks @kzantow)

### CODE REVIEW

**Comment by esaruoho** [comment]
@kurasu @abique I've finished work on this translation, and it is ready to go. Please let me know if I should change something, clarify something, remove something (if *all* the translations are done 100% correctly, should I altogether remove all the swedish comments?).. or something. 

Would love to get this merged in - if possible - because it's easier for non-Swedish speakers to understand and take the software further if they don't have to screw around with Swedish.

**Comment by baconpaul** [comment]
Tack! (That’s thank you in Swedish, right?)

**Comment by esaruoho** [comment]
@baconpaul i'm actually Finnish so kiitos is tack in Finnish :)

**Comment by esaruoho** [comment]
Added @baconpaul 's quickfix from #89 for mac.( link to commit https://github.com/baconpaul/surge/commit/e5737f0785141147995d57e1d5637a0001c9f183 )

**Comment by kzantow** [comment]
@esaruoho fix for #77 is https://github.com/kurasu/surge/pull/87/commits/7be524369a4226c54dffad40b85eef63ecb5f8f0

**Comment by esaruoho** [comment]
@kzantow thanks, i'll add that to #68 too!

**Comment by baconpaul** [comment]
I think we should maybe just have one big pull request which gets us to zoomable ui plus all your fixes then give the maintainers one thing to review rather than these scattered cross commits I have one commitnfor the logo display but otherwise my code is done and meegable

Would someone like to take a crack at making a branch which rldoes these merges or making a super pr?

**Comment by kzantow** [comment]
@baconpaul I agree, it would be much easier to review and fix in one spot. I can make a PR with all the combined stuff later today

**Comment by baconpaul** [comment]
Great and then we can close the rest and all avoid branching hell!

Baconpaul branch “zoomable-ui” contains all my changes including the stuff in #69 but like I said I have a 2 line change to commit and I’m out and about now so if you can either give me perms to add to the pr or prep for one last commit that would be great.

Fun stuff! Thank you

  - Paul

On Dec 16, 2018, at 12:14, Keith Zantow <notifications@github.com<mailto:notifications@github.com>> wrote:


@baconpaul<https://github.com/baconpaul> I agree, it would be much easier to review and fix in one spot. I can make a PR with all the combined stuff later today

**Comment by esaruoho** [comment]
PR #70 content added

**Comment by baconpaul** [comment]
Oooh that diff is a bit odd.  I would not include that.

Which pull request are we using for the "master"? Shall we just use #69? I am happy to add zoomable-ui to that now and then for the rest to get added in?

**Comment by esaruoho** [comment]
@baconpaul yeah i was doing my head in trying to cherry-pick commits from this branch into another branch, but i just don't know enough git-fu to get rid of that diff or to remove it from the branch or something. really confusing. i wish i knew how.

**Comment by baconpaul** [comment]
From https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request

```
# Checkout the desired branch
git checkout <branch>

# Undo the desired commit
git revert <commit>

# Update the remote with the undo of the code
git push origin <branch>
```

where <branch> is the branch in your forked repo with all of this and <commit> is c4c6a08

but at some points in git merge hell it's easier to start a new branch and remerge and redo a PR. Which is why branching is a bit tricky when dev cadence is faster than merge cadence.

**Comment by esaruoho** [comment]
@baconpaul hmm.. i'm getting this

```
$ git revert c4c6a08
error: commit c4c6a08ed3f14ddab06e98d29a06c74b8174524f is a merge but no -m option was given.
fatal: revert failed
```
and

```
$ git revert -m c4c6a08
error: option `mainline' expects a number greater than zero
```

and
```
$ git revert c4c6a08ed3f14ddab06e98d29a06c74b8174524f
error: commit c4c6a08ed3f14ddab06e98d29a06c74b8174524f is a merge but no -m option was given.
fatal: revert failed
```

and

```
$ git revert -m c4c6a08ed3f14ddab06e98d29a06c74b8174524f
error: option `mainline' expects a number greater than zero
```

.. ouch

**Comment by baconpaul** [comment]
Yuck. I’m not sure then.

**Comment by esaruoho** [comment]
maybe if i could figure out a way of making a new branch from say, your branch, then i could start rebuilding a new PR. i'll investigate this tomorrow. mind you, it might be trivial for @kurasu to just remove the diff or something, but.. i guess we'll be wiser come monday-wednesday.

**Comment by baconpaul** [comment]
@esaruoho looks like @kzantow has got most of this pulled into his #92 without this weird diff. He definitely got all of my key changes into that PR and I closed #69 as a result. So perhaps close this one too and then we can just all use his #92 for the review and merge to get zoomable documented etc... all in place.

**Comment by esaruoho** [comment]
all this everything in #92, so closing.

**Pull request closed without merging**
