### PR TITLE
#183 ("Suggestion: fix sorting of patches in submenus to be A->Z?")

### PR DESCRIPTION
**Pull request by jsakkine**

### CODE REVIEW

**Comment by jsakkine** [comment]
Please actually review the code changes. Simple stuff but touches category indices, which are spread all around the code base so better be careful here.

**Comment by baconpaul** [comment]
Ok I can’t compile this until into 19 but did a scan with one immediate question. 

I’m not sure a partial change from this_name to thatName names the code more readable either. I will ponder that

**Comment by jsakkine** [comment]
@baconpaul, That is how the coding style is usually changed in large open source projects. You apply the new style when you do something more useful in order to keep commit diffs nice and compact. It is well considered why I did not rename anything else. I'd guess camelCase for member variables is way to go?

**Comment by baconpaul** [comment]
Oh yeah the two var array is a good change. I was wondering why you eliminated the little single element structure in my review

I think you are right in naming changes. But we do need a standard! Otherwise we will keep discussing it in prs :)

**Comment by jsakkine** [comment]
For this particular class we could do one "rename commit" soonish e.g. `load_wt()` to `loadWaveTable()` and so forth. It has its tentacles everywhere. Much more important to have clean code than lets say in the code of one purpose UI component.

**Comment by jsakkine** [comment]
I eliminated the one element structure essentially because it brings no value and map or vector of strings is easier data structure for the last change.

**Comment by baconpaul** [comment]
Hmm ... well it adds symmetry and extensibility - if/when we add more info about categories we have a place to hang it. I rather liked the little structure for these reasons!

**Comment by jsakkine** [comment]
OK, fair enough :) But I'll hold up until the current version is tested before changing anything. Would suggest then rename it simply as `struct Category`.

**Comment by jsakkine** [comment]
Does it work out, though?

**Comment by jsakkine** [comment]
My stand on removing that struct. If it is not used, then it is not used. If we need to have something fancier than just `std::string`, we should introduce it in that point. Now that struct only introduces complexity and does not bring value. Only when you need to extend something you'll know what you actually need. "just in-case" things usually don't work out. I could understand it if that was part of API/ABI but we don't have such constraints. Not going to argue hugely about it and can update the patch set not to remove it but does it make any sense?

**Comment by baconpaul** [comment]
Still no laptop 

But I have a use for the strict to fix some of the saving issues kicking around. Would be good to be able to ask things like if a category is factory. So if it works I will restore the struct squash and push. But not until I get a machine with a compiler!

**Comment by jsakkine** [comment]
@baconpaul, That is why I was asking for code review to get feedback what to do with it. I was wondering why the original issue was asking to only sort categories but I just realized that I've misread issue title. Also, it was not obvious if over-length was part of the issue or not.

Can you also tell what is wrong how the categories are sorted wrong at the moment when you say that "it sorts some of the categories"? It does sort all of the categories in three groups (factory, 3rd party and user).

I rework with this but yeah I was on hold for feedback for some time (no one had tried it before you).

**Comment by jsakkine** [comment]
And keeping that microstruct is not like a show stopper for me. I can take it back but if we have it maybe it would not be a bad idea to have all data that describes a category in it. Then it would probably be more future-proof e.g.

```
struct Category {
   int id;
   std::string name;
}
```
This can be more easily kept in different types of data hierarchies and do same queries (linked list, vector, map in sorted or unsorted form).

**Comment by jsakkine** [comment]
Yes, I get that design.

Here's what I propose:

1. Lets close this PR with the commit from my just rebased master with just the accepted commit.
2. I'll create a feature branch called `menusort` to my tree and work out something that I see appropriate based on your suggestion.
3. Then we figure out the rest.

**Comment by baconpaul** [comment]
Great. Tested it all built so merging it in now. Thanks!

**Pull request merged**
