### PR TITLE
Fix the paint bit order issues for the step sequencer

### PR DESCRIPTION
**Pull request by baconpaul**
Hey if someone could just eyeball this for me when you have a moment (@jsakkine @kzantow @esaruoho @asimilon maybe?) it fixes the step sequencer UI on mac, as described in #141. Wouldn't mind a quick once over before I push it just to make sure I didn't screw up the constants, even though I'm pretty confident.

Thanks!

### CODE REVIEW

**Comment by jsakkine** [comment]
I would prefer 

```
#ifdef MAC
// declarations
#else
// declarations
#endif 
```

About the same amount of lines. No reason to be too smart here. Maybe in the long run this could be handled with some kind of theming...

**Comment by baconpaul** [comment]
Yeah I almost did that - the other places I fixed this bug I did - but the reason I didn't was to avoid adding or changing a color in one platform and not the other. I figured the higher risk was "we change mac and not windows" not that "we have a bit of splattage". So no way we can add a variable in "only one branch". Also then I can visually check those strings are the same just transposed line by line.

If you feel really strongly (I don't feel really strongly - it was a 55/45 type thing with me) I can change it.

I agree in the long run this needs to be themed. That's "a lot of work" but not as much as porting to juce :)

**Comment by jsakkine** [comment]
Not really a biggie for me. Either way will work. We cannot have anything solid for this right now. I just said what I had in mind because you asked for it :)

**Comment by baconpaul** [comment]
Sanity checking is why we do reviews! Appreciate it. If it falls in the camp of not a biggie and looks ok otherwise I’ll merge it for now and we will revisit when we think skins and there’s (see #91 for some on that)

Thanks for the eyeball!’

**Comment by asimilon** [comment]
> `#ifdef MAC`

should use `#if MAC`, as is the convention throughout rest of code, also I'm not sure about the VS project, but in the XCode project the preprocessor macros are: 

image

so, if the same applies to the VS project, `#ifdef` is going to evaluate true always.

**Comment by baconpaul** [comment]
Oh thank you! I will patch this.

**Comment by asimilon** [comment]
I had a look at `premake5.lua` and it looks to me like `MAC=1` should only actually be in the XCode project, so it's most likely not an issue.

**Comment by baconpaul** [comment]
Yeah maybe. But I patched it anyway for consistency.

And now I'm really off for the day :)

Thanks!

**Pull request merged**
